services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./app:/app
      - ./app/uploads:/app/uploads
    ports:
      - "8080:8080"
    environment:
      - ENV=production
      - MONGO_URI=mongodb://db:27017
      - DB_NAME=doolar
    depends_on:
      - db
  
  whisper-asr:
    build: 
      context: ./whisper
      dockerfile: ./Dockerfile
    container_name: whisper-asr
    environment:
      WHISPER_MODEL: small
      WHISPER_LANGUAGE: pt
      WHISPER_DEVICE: cpu
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./whisper/app:/app
    working_dir: /app
  
  db:
    container_name: db
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root

networks:
  default:
    driver: bridge

volumes:
  db-data: {}